import esbuild from 'esbuild';
import builtins from 'builtin-modules';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));

/* Obsidian loads main.js from the same folder as manifest.json and styles.css,
 * so those three travel together — to the repo root for a release build, to a
 * vault's plugin folder for development. */
const ASSETS = ['manifest.json', 'styles.css'];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source, issues and licence: https://github.com/Jin1c-3/obsidian-advanced-maps
*/
`;

/* A four-line .env reader, so `npm run dev` needs no global env var and no
 * dotenv dependency. Real environment variables win over the file. */
function loadEnv() {
	const file = path.join(root, '.env');
	if (!fs.existsSync(file)) return;
	for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
		const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/.exec(line);
		if (!match || line.trim().startsWith('#')) continue;
		if (process.env[match[1]] === undefined) {
			process.env[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
		}
	}
}

function vaultDir() {
	const dir = process.env.OBSIDIAN_PLUGIN_DIR;
	return dir && dir.trim() ? path.resolve(dir.trim()) : null;
}

function copyAssets(outDir) {
	if (path.resolve(outDir) === root) return;
	fs.mkdirSync(outDir, { recursive: true });
	for (const name of ASSETS) fs.copyFileSync(path.join(root, name), path.join(outDir, name));
}

/* pjeby's Hot Reload plugin only reloads plugins whose folder holds a
 * `.hotreload` marker, so put one there rather than asking the reader to. */
function markHotReload(outDir) {
	const marker = path.join(outDir, '.hotreload');
	if (!fs.existsSync(marker)) fs.writeFileSync(marker, '');
}

loadEnv();

const mode = process.argv[2] ?? 'dev';
const prod = mode === 'production';
const deploy = process.argv.includes('--deploy');

let outDir = root;
if (!prod || deploy) outDir = vaultDir() ?? root;
if (deploy && !vaultDir()) {
	console.error('Set OBSIDIAN_PLUGIN_DIR (see .env.example) before running `npm run deploy`.');
	process.exit(1);
}

const context = await esbuild.context({
	entryPoints: [path.join(root, 'src/main.ts')],
	outfile: path.join(outDir, 'main.js'),
	bundle: true,
	format: 'cjs',
	target: 'es2018',
	platform: 'browser',
	logLevel: 'info',
	treeShaking: true,
	sourcemap: prod ? false : 'inline',
	minify: prod,
	banner: { js: banner },
	// Everything Obsidian injects at runtime, plus the editor packages a plugin
	// may import. Bundling any of them ships a second copy that breaks identity
	// checks against the host's.
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
});

copyAssets(outDir);
// Any write into a vault is a development install, so leave the marker there
// whichever route got us here.
if (path.resolve(outDir) !== root) markHotReload(outDir);

if (prod) {
	await context.rebuild();
	await context.dispose();
	console.log(`built → ${path.join(outDir, 'main.js')}`);
} else {
	// Assets change far less often than the bundle, but a manifest version bump
	// mid-session should still land in the vault.
	for (const name of ASSETS) {
		fs.watch(path.join(root, name), () => copyAssets(outDir));
	}
	await context.watch();
	console.log(`watching → ${path.join(outDir, 'main.js')}`);
}
